# labs/lab-003-vwan-aws-vpn-bgp-apipa/aws/variables.tf

variable "aws_region" {
  description = "AWS region for resources"
  type        = string
  default     = "us-east-2"
}

variable "lab_prefix" {
  description = "Prefix for resource naming"
  type        = string
  default     = "lab-003"
}

variable "vpc_cidr" {
  description = "CIDR block for AWS VPC"
  type        = string
  default     = "10.20.0.0/16"
}

variable "public_subnet_cidr" {
  description = "CIDR block for public subnet"
  type        = string
  default     = "10.20.1.0/24"
}

variable "aws_bgp_asn" {
  description = "BGP ASN for AWS side (VGW)"
  type        = number
  default     = 65001
}

variable "azure_bgp_asn" {
  description = "BGP ASN for Azure side (for Customer Gateway)"
  type        = number
  default     = 65515
}

# Azure VPN Gateway public IPs (passed from Azure deployment)
variable "azure_vpn_gateway_ip_1" {
  description = "First public IP of Azure VPN Gateway"
  type        = string
}

variable "azure_vpn_gateway_ip_2" {
  description = "Second public IP of Azure VPN Gateway (optional)"
  type        = string
  default     = ""
}

# Pre-shared keys (generated by deploy script)
variable "psk_vpn1_tunnel1" {
  description = "Pre-shared key for VPN1 Tunnel 1"
  type        = string
  sensitive   = true
}

variable "psk_vpn1_tunnel2" {
  description = "Pre-shared key for VPN1 Tunnel 2"
  type        = string
  sensitive   = true
}

variable "psk_vpn2_tunnel1" {
  description = "Pre-shared key for VPN2 Tunnel 1 (Tunnel 3)"
  type        = string
  sensitive   = true
  default     = ""
}

variable "psk_vpn2_tunnel2" {
  description = "Pre-shared key for VPN2 Tunnel 2 (Tunnel 4)"
  type        = string
  sensitive   = true
  default     = ""
}

# APIPA inside tunnel IPs for BGP
variable "tunnel1_inside_cidr" {
  description = "Inside CIDR for VPN1 Tunnel 1 (AWS side APIPA)"
  type        = string
  default     = "169.254.21.0/30"
}

variable "tunnel2_inside_cidr" {
  description = "Inside CIDR for VPN1 Tunnel 2 (AWS side APIPA)"
  type        = string
  default     = "169.254.22.0/30"
}

variable "tunnel3_inside_cidr" {
  description = "Inside CIDR for VPN2 Tunnel 1 (AWS side APIPA) - connects to Azure Instance 1"
  type        = string
  default     = "169.254.23.0/30"
}

variable "tunnel4_inside_cidr" {
  description = "Inside CIDR for VPN2 Tunnel 2 (AWS side APIPA) - connects to Azure Instance 1"
  type        = string
  default     = "169.254.24.0/30"
}

variable "tags" {
  description = "Tags for all resources (lowercase keys required)"
  type        = map(string)
  default = {
    project = "azure-labs"
    lab     = "lab-003"
    env     = "lab"
  }
}

variable "owner" {
  description = "Owner tag for resource tracking (optional)"
  type        = string
  default     = ""
}

variable "allowed_regions" {
  description = "Allowlist of AWS regions where this lab can be deployed"
  type        = list(string)
  default     = ["us-east-1", "us-east-2", "us-west-2", "eu-west-1"]
}

locals {
  # Merge owner into tags if provided
  all_tags = var.owner != "" ? merge(var.tags, { owner = var.owner }) : var.tags
}
